# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g @angular/cli
  displayName: 'npm install'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'karlosarr'
    scannerMode: 'MSBuild'
    projectKey: 'karlosarr_api-jaxitank-react-demo'
    projectName: 'karlosarr_api-jaxitank-react-demo'
  displayName: 'Prepare scan with SonarCloud'

- task: SonarCloudAnalyze@1
  displayName: 'Scan with SonarCloud'

- script: |
    ng build --prod
  displayName: 'Generate binary'